FLearningg/Flearning_BE

- BackEnd/models/cartModel.js
- BackEnd/models/categoryModel.js
- BackEnd/models/chatModel
- BackEnd/models/commentModel.js
- BackEnd/models/conversationModel.js
- BackEnd/models/courseModel.js
- BackEnd/models/discountModel.js
- BackEnd/models/lectureModel.js
- BackEnd/models/lessonModel.js
- BackEnd/models/notificationModel.js
- BackEnd/models/progressModel.js
- BackEnd/models/sectionModel.js
- BackEnd/models/userModel.js
- BackEnd/models/wishlistModel.js
> [FLN-59][BE][Feat] Add FLearning Model

- BackEnd/models/cartModel.js
- BackEnd/models/categoryModel.js
- BackEnd/models/chatModel.js
- BackEnd/models/commentModel.js
- BackEnd/models/conversationModel.js
- BackEnd/models/courseModel.js
- BackEnd/models/discountModel.js
- BackEnd/models/lectureModel.js
- BackEnd/models/lessonModel.js
- BackEnd/models/notificationModel.js
- BackEnd/models/progressModel.js
- BackEnd/models/sectionModel.js
- BackEnd/models/userModel.js
- BackEnd/models/wishlistModel.js
> [FLN-75][Hoang][UI] Update model for FLearning [18.06.2025]

- BackEnd/controllers/cartController.js
- BackEnd/controllers/wishlistController.js
- BackEnd/routes/cartRoutes.js
- BackEnd/routes/wishlistRoutes.js
- BackEnd/server.js
**Overview**
Thêm mới back-end cho xem, thêm , xóa cart và wishlist
**Checklists**
**Jira Link**
https://flearning.atlassian.net/browse/FLN-66
> [feat][FLN-66][BE] Add Cart & Wishlist API

- .gitignore
- BackEnd/controllers/cartController.js
- BackEnd/controllers/categoryController.js
- BackEnd/controllers/courseController.js
- BackEnd/controllers/notificationController.js
- BackEnd/controllers/wishlistController.js
- BackEnd/package.json
- BackEnd/routes/categoryRoutes.js
- BackEnd/routes/courseRoutes.js
- BackEnd/routes/notificationRoutes.js
- BackEnd/routes/userRoutes.js
- BackEnd/server.js
**Overview**
Thêm mới back-end cho xem tất cả course, search course dựa trên title và description, lấy tất cả top category (limit 12 result), 
xem tất cả notification
**Checklists**
**Jira Link**
https://flearning.atlassian.net/browse/FLN-62
> [FLN-62][BE] Add Course, categories, notification API

- BackEnd/controllers/feedbackController.js
- BackEnd/models/discountModel.js
- BackEnd/models/feedbackModel.js
- BackEnd/routes/feedbackRoutes.js
- BackEnd/server.js
**Overview :**
Thêm tính năng xem, thêm, sửa, xóa feedback 
**Checklists**
> [FLN-64][BE] Add Feedback API

- .github/workflows/deploy-backend.yml
- .github/workflows/test-flearning-be.yml
- BackEnd/.gitignore
- BackEnd/.prettierignore
- BackEnd/.prettierrc.json
- BackEnd/package.json
- Xoá file package.json và gitignore ở ngoài
- Thêm prettier và eslint tự động format code
- thêm CI/CD cho FLearning FE
---
**Checklists**
---
---
> [refactor][Hoang] Update ci/cd and big update format

- BackEnd/controllers/authController.js
> [BE] Check banned user can't login 

- BackEnd/controllers/adminController.js
- BackEnd/controllers/firebaseController.js
- BackEnd/middlewares/uploadMiddleware.js
- BackEnd/models/lessonModel.js
- BackEnd/models/sectionModel.js
- BackEnd/package.json
- BackEnd/routes/adminRoutes.js
- BackEnd/server.js
- BackEnd/utils/cleanup-temp-files.js
- BackEnd/utils/firebaseStorage.js
- COMMENT_RULES.md
**Overview**
Thêm mới API cho admin manage user, course, section và lesson
**Checklists**
**Jira Link**
https://flearning.atlassian.net/browse/FLN-70
> Draft:[feat][FLN-70][API] Add admin API 

- BackEnd/middlewares/driveMiddleware.js
- BackEnd/routes/authRoutes.js
- BackEnd/routes/cartRoutes.js
- BackEnd/routes/profileRoutes.js
- Fix Route import 
- Fix middleware driver and firebase 
---
**Checklists**
---
---
> [Hoang][UI] HOTFIX Route and Middle ware merge 26.06 [26.06.2025]

- BackEnd/controllers/adminController.js
- BackEnd/controllers/categoryController.js
- BackEnd/models/courseModel.js
- BackEnd/routes/adminRoutes.js
- BackEnd/utils/firebaseStorage.js
- Format tên video
- Thay đổi modal course để thêm category
---
**Checklists**
---
---
> [bugfix][BE] Fix bug upload video

- BackEnd/controllers/categoryController.js
- BackEnd/models/categoryModel.js
- Thay đổi modal category để thêm trường icon (sử dụng bootstrap icon name chỉ lấy tiền tố sau)
- VD: className="bi bi-code-slash"    ||      => icon: "bi-code-slash"
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-78
> [Enhancement][BE] Add thêm trường icon để nhập icon (bootstrap icon name)

- BackEnd/controllers/courseController.js
**Overview**
Fix lại getAllCourse, bestSellingCourse, recentAddedCourse sau khi thay đổi categoryModel
(categoryId ----> categoryIds)
**Checklists**
**Jira**
https://flearning.atlassian.net/browse/FLN-80
> [FLN-80][BE] Fix update controller after change category model

- BackEnd/controllers/profileController.js
**Overview**
Sửa API để fetch được data ra FE
**Checklists**
**EVD**
> [FLN-83][BE] Fix API to fetch data for Purchase History, Student Dashboard, My Course

- BackEnd/controllers/cartController.js
- BackEnd/controllers/wishlistController.js
**Overview**
Sửa logic API thêm populate để lấy hết data
**Checklists**
> [FLN-84][BE] Fix lỗi không populate hết data

- BackEnd/controllers/notificationController.js
- BackEnd/routes/notificationRoutes.js
- Add new API update all readStatus
- Public API for admin and student
- Format code
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-88
> [FLN-88][BE] Format code, add api update all readStatus, public api for admin and student

- BackEnd/controllers/courseDetailsController.js
- BackEnd/routes/courseRoutes.js
Overview:
+ Fix route for api course detail
+ Handle data when fetch api course detail
> [FLN-93][Thien][BE] Fix course details api

- BackEnd/controllers/progressController.js
- BackEnd/routes/progressRoutes.js
- BackEnd/server.js
**Overview**
- Thêm api để track Course Progress
**Checklists**
> [FLN-92][BE] Add API to track Course Progress

- BackEnd/controllers/adminController.js
- BackEnd/controllers/chatbotController.js
**Checklists**
**Overview**:
- Đổi API Admin Stats và update Prompt Gemini
> [Dat][API] Update Admin stats API 

- BackEnd/controllers/courseController.js
**Overview**
+ Truyền vào một mảng courseId để thêm vào enrolledCourses
**Checklists**
**Jira**
https://flearning.atlassian.net/browse/FLN-97
**EVD**
> [FLN-97][API][BE][Fix] Thay đổi có thể enroll nhiều course cùng lúc

- BackEnd/controllers/paymentController.js
- BackEnd/routes/courseRoutes.js
- BackEnd/routes/paymentRoutes.js
- BackEnd/server.js
Overview :
+ Add payment API
+ Remove token auth of /enroll-course
> [FLN-68][Thien][BE] Add Payment API

- BackEnd/server.js
- Thay đổi code handle việc chat realtime
---
**Checklists**
---
https://flearning.atlassian.net/browse/FLN-95
---
> [FLN-95][Hoang][BE] Handle real time chat [14.07.2025]

- BackEnd/controllers/authController.js
- BackEnd/models/userModel.js
- BackEnd/routes/authRoutes.js
Overview:
- Thêm 2 API để Forget Password React-native
**Checklists**
> [API] Mobile Forgot Password

- BackEnd/controllers/authController.js
- BackEnd/models/userModel.js
- BackEnd/routes/authRoutes.js
Overview:
refractor authController thành English
> refractor authController thành English

- BackEnd/controllers/feedbackController.js
- BackEnd/models/feedbackModel.js
- BackEnd/routes/feedbackRoutes.js
**Overview**
- Thêm API để tính rate trung bình của 1 course
**Checklists**
> [FLN][Duc][BE] Add API to calculate average rating for course

- BackEnd/controllers/adminController.js
- BackEnd/controllers/chatbotController.js
> [API] Chatbot Update
